  # TP PLAYBOOK - INVENTAIRE

  ## Gestion de l'inventaire 
    
    - le serveur client de type debian doit faire parti d'un groupe de l'inventaire appelé web 
    
  ## Création d'un palybook

    - Fichier yaml : tp1-web-playbook.yaml
    
    - Target : web
    
    - Installe les packages : (module ???)
      - git
      - vim
      - apache2
      
    - S'assurer que le service apache2 soit activé (enable) et démaré (module ???)
    
    - Copie un fichier "static" index.html (présent dans le projet ansible) vers /var/www/html (module ??? ) 